language: node_js
sudo: false
node_js:
    - "6"
before_install:
    - rvm install 2.2.2
before_script:
    - gem install sass
    - gem install compass
    - npm install -g grunt-cli
before_deploy:
    - git config --global user.email "test@travis-ci.org"
    - git config --global user.name "Travis"
    - git fetch --unshallow
    - git add dist -f
    - git commit -m "add compiled assets"
deploy:
    provider: heroku
    api_key:
        secure: L5NF8otPnfci4wA1dhaJgcwouRZP7ZKqfCbJYIZ4bWeO3+siTwwqHfnL1k24w2GeO6ZB4H4ONHG8dD6mDtuGrwgLf92Y/PUc+NgAiE4J68+7K7o4h3GI/zAp61Skv/UIbWQg4H2wIdYDAmh+5oXYy2LSonNSdQyW4u5HDkbLDNY=
    app: energiatieto-2-0
    strategy: git
    skip_cleanup: true
    on:
        branch: master
        repo: lauripiispanen/energiatieto-2.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
